# Generated by Django 4.2.26 on 2025-11-19 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_membership_core_member_user_id_5b6d13_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('client_name', models.CharField(db_index=True, max_length=255, verbose_name='client name')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='client email')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='client phone')),
                ('client_company', models.CharField(blank=True, max_length=255, verbose_name='client company')),
                ('project_type', models.CharField(choices=[('FIXED_PRICE', 'Fixed Price'), ('TIME_AND_MATERIALS', 'Time & Materials'), ('RETAINER', 'Retainer'), ('OTHER', 'Other')], db_index=True, default='TIME_AND_MATERIALS', max_length=30, verbose_name='project type')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total project budget', max_digits=12, null=True, verbose_name='budget')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], db_index=True, default='VIEWER', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborators', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'project collaborator',
                'verbose_name_plural': 'project collaborators',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborated_projects', through='projects.ProjectCollaborator', to=settings.AUTH_USER_MODEL, verbose_name='collaborators'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddIndex(
            model_name='projectcollaborator',
            index=models.Index(fields=['project', 'role'], name='projects_pr_project_b7033c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaborator',
            index=models.Index(fields=['user', 'role'], name='projects_pr_user_id_b8847e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcollaborator',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='projects_pr_organiz_8941e0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='projects_pr_owner_i_4798b7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_name'], name='projects_pr_client__447719_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'status'], name='projects_pr_is_acti_189799_idx'),
        ),
    ]
