# Generated by Django 4.2.23 on 2025-07-28 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_membership_core_member_user_id_5b6d13_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
            ],
            options={
                'verbose_name': 'workspace',
                'verbose_name_plural': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], db_index=True, default='VIEWER', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_collaborators', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'workspace collaborator',
                'verbose_name_plural': 'workspace collaborators',
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborated_workspaces', through='workspaces.WorkspaceCollaborator', to=settings.AUTH_USER_MODEL, verbose_name='collaborators'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='core.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddIndex(
            model_name='workspacecollaborator',
            index=models.Index(fields=['workspace', 'role'], name='workspaces__workspa_260698_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecollaborator',
            index=models.Index(fields=['user', 'role'], name='workspaces__user_id_2eff1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacecollaborator',
            unique_together={('workspace', 'user')},
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['organization', 'status'], name='workspaces__organiz_a472da_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'status'], name='workspaces__owner_i_4e18fe_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['is_active', 'status'], name='workspaces__is_acti_25d9b5_idx'),
        ),
    ]
