# Generated by Django 4.2.23 on 2025-07-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_system_workspace',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this workspace is a system workspace.', verbose_name='system workspace'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='workspace_type',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('TEAM', 'Team'), ('PROJECT', 'Project'), ('PERSONAL', 'Personal')], db_index=True, default='TEAM', max_length=20, verbose_name='workspace type'),
        ),
    ]
