# Generated by Django 4.2.26 on 2025-11-19 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('model_type', models.CharField(choices=[('TEXT', 'Text'), ('CODE', 'Code'), ('IMAGE', 'Image'), ('VOICE', 'Voice'), ('VIDEO', 'Video')], db_index=True, default='TEXT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('context_session_id', models.UUIDField(blank=True, db_index=True, help_text='Reference to universal context session', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_sessions', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'prompt session',
                'verbose_name_plural': 'prompt sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('input_text', models.TextField(verbose_name='input text')),
                ('execution_metadata', models.JSONField(blank=True, default=dict, help_text='Model execution details, optimization strategy, etc.', verbose_name='execution metadata')),
                ('importance_score', models.FloatField(default=1.0, help_text='Importance score for prioritization and cleanup')),
                ('is_starred', models.BooleanField(default=False, help_text='User-starred prompt (Enterprise feature)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='prompt.promptsession', verbose_name='session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_prompts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['project', 'status'], name='prompt_prom_project_22e83f_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['creator', 'status'], name='prompt_prom_creator_747d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['model_type', 'status'], name='prompt_prom_model_t_d32039_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['is_active', 'status'], name='prompt_prom_is_acti_efe2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['context_session_id'], name='prompt_prom_context_656ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['session', '-created_at'], name='prompt_prom_session_4b4fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['user', '-created_at'], name='prompt_prom_user_id_2de7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['importance_score'], name='prompt_prom_importa_ee5077_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_starred', '-created_at'], name='prompt_prom_is_star_29a725_idx'),
        ),
    ]
