# Generated by Django 4.2.23 on 2025-07-30 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_membership_core_member_user_id_5b6d13_idx_and_more'),
        ('workspaces', '0002_workspace_is_system_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorageBackend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('backend_type', models.CharField(choices=[('gcp_storage', 'Google Cloud Storage'), ('local', 'Local Storage')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict, help_text='Backend configuration (bucket name, credentials path, etc.)')),
                ('max_file_size_mb', models.PositiveIntegerField(default=50)),
                ('allowed_extensions', models.JSONField(default=list, help_text="Allowed file extensions: ['.pdf', '.docx', '.txt', '.md', '.csv']")),
            ],
            options={
                'verbose_name': 'File Storage Backend',
                'verbose_name_plural': 'File Storage Backends',
                'db_table': 'file_storage_backend',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('original_filename', models.CharField(db_index=True, max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('file_extension', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('user_document', 'User Document'), ('workspace_document', 'Workspace Document'), ('rag_document', 'RAG Document'), ('agent_asset', 'Agent Asset'), ('workflow_asset', 'Workflow Asset')], db_index=True, default='user_document', max_length=30)),
                ('access_level', models.CharField(choices=[('private', 'Private (Owner Only)'), ('workspace', 'Workspace Members'), ('organization', 'Organization Members')], db_index=True, default='private', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('storage_path', models.TextField()),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash for deduplication', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text content for RAG processing')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='core.organization')),
                ('storage_backend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='file_storage.filestoragebackend')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'db_table': 'file_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('job_type', models.CharField(choices=[('text_extraction', 'Text Extraction'), ('rag_embedding', 'RAG Embedding')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='file_storage.fileupload')),
            ],
            options={
                'verbose_name': 'File Processing Job',
                'verbose_name_plural': 'File Processing Jobs',
                'db_table': 'file_processing_job',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['organization', 'purpose', 'is_active'], name='file_upload_organiz_dfa375_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['workspace', 'is_active'], name='file_upload_workspa_dcc592_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='file_upload_uploade_e4baa7_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['status'], name='file_upload_status_20c17f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_hash'], name='file_upload_file_ha_eb7bde_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['access_level'], name='file_upload_access__a695b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileupload',
            constraint=models.UniqueConstraint(fields=('organization', 'file_hash'), name='unique_file_per_org'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['file_upload', 'job_type'], name='file_proces_file_up_ef2f20_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='file_proces_status_8a5541_idx'),
        ),
    ]
