# Generated by Django 4.2.26 on 2025-11-19 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('core', '0002_remove_membership_core_member_user_id_5b6d13_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='projects.project'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='storage_backend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='file_storage.filestoragebackend'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileprocessingjob',
            name='file_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='file_storage.fileupload'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='core.organization'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='file_storage.filefolder'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['organization', 'purpose', 'is_active'], name='file_upload_organiz_dfa375_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['project', 'is_active'], name='file_upload_project_e5f315_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='file_upload_uploade_e4baa7_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['status'], name='file_upload_status_20c17f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_hash'], name='file_upload_file_ha_eb7bde_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['access_level'], name='file_upload_access__a695b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileupload',
            constraint=models.UniqueConstraint(fields=('organization', 'file_hash'), name='unique_file_per_org'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['file_upload', 'job_type'], name='file_proces_file_up_ef2f20_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='file_proces_status_8a5541_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['organization', 'project', 'parent_folder'], name='file_folder_organiz_a244a4_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['created_by'], name='file_folder_created_593fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['access_level'], name='file_folder_access__c0e4c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(fields=('name', 'parent_folder', 'project', 'organization'), name='unique_folder_per_location'),
        ),
    ]
