# Generated by Django 4.2.25 on 2025-10-10 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_is_system_workspace_and_more'),
        ('core', '0002_remove_membership_core_member_user_id_5b6d13_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('access_level', models.CharField(choices=[('private', 'Private (Owner Only)'), ('workspace', 'Workspace Members'), ('organization', 'Organization Members')], db_index=True, default='private', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='core.organization')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='file_storage.filefolder')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'File Folder',
                'verbose_name_plural': 'File Folders',
                'db_table': 'file_folder',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fileupload',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_storage.filefolder'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['organization', 'workspace', 'parent_folder'], name='file_folder_organiz_2a57b3_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['created_by'], name='file_folder_created_593fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['access_level'], name='file_folder_access__c0e4c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(fields=('name', 'parent_folder', 'workspace', 'organization'), name='unique_folder_per_location'),
        ),
    ]
