# Generated by Django 4.2.26 on 2025-11-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_membership_core_member_user_id_5b6d13_idx_and_more'),
        ('prompt', '0001_initial'),
        ('modelhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmetrics',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Prompt session associated with this metric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='prompt.promptsession'),
        ),
        migrations.AddField(
            model_name='model',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhub.provider'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='If null, this is a system-wide API key', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhub.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='routingrulemodel',
            unique_together={('rule', 'model')},
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['model', 'timestamp'], name='modelhub_mo_model_i_b73c25_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['organization', 'timestamp'], name='modelhub_mo_organiz_819f18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('provider', 'name', 'version')},
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('provider', 'label'), name='unique_system_apikey'),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('organization', 'provider', 'label')},
        ),
    ]
