# Generated by Django 4.2.23 on 2025-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='embedding_dimensions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='embedding_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='supports_embeddings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('CODE', 'Code'), ('IMAGE', 'Image'), ('VOICE', 'Voice'), ('VIDEO', 'Video'), ('EMBEDDING', 'Embedding Model')], max_length=20),
        ),
    ]
