# Generated by Django 4.2.24 on 2025-10-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelhub', '0002_model_embedding_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='cost_image',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost per image in USD (for vision models)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='vision_max_image_size',
            field=models.IntegerField(blank=True, help_text='Maximum image size in pixels (width or height)', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='vision_max_images',
            field=models.IntegerField(blank=True, help_text='Maximum number of images per request', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='vision_supported_formats',
            field=models.JSONField(blank=True, default=list, help_text='List of supported image formats (e.g., ["png", "jpeg", "webp"])'),
        ),
        migrations.AddField(
            model_name='modelmetrics',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='supports_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='vision_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('CODE', 'Code'), ('IMAGE', 'Image'), ('VOICE', 'Voice'), ('VIDEO', 'Video'), ('EMBEDDING', 'Embedding Model'), ('VISION', 'Vision Model')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='model_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('CODE', 'Code'), ('IMAGE', 'Image'), ('VOICE', 'Voice'), ('VIDEO', 'Video'), ('VISION', 'Vision'), ('EMBEDDING', 'Embedding')], max_length=20),
        ),
    ]
