# Generated by Django 4.2.26 on 2025-11-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeoff', '0003_add_page_number_and_extraction_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='takeoffelement',
            new_name='takeoff_ele_page_nu_388321_idx',
            old_name='takeoff_ele_page_nu_idx',
        ),
    ]
