# Generated by Django 4.2.25 on 2025-10-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_service', '0002_add_complete_document_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='rag_documen_storage_7d270b_idx',
            old_name='rag_documen_storage_f6e2c2_idx',
        ),
    ]
