# Generated by Django 4.2.25 on 2025-10-23 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rag_service', '0003_rename_rag_documen_storage_f6e2c2_idx_rag_documen_storage_7d270b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('page_number', models.IntegerField()),
                ('page_text', models.TextField(blank=True)),
                ('layout_blocks', models.JSONField(blank=True, default=list)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('rotation', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('token_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('table_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='rag_service.document')),
            ],
            options={
                'verbose_name': 'Document Page',
                'verbose_name_plural': 'Document Pages',
                'db_table': 'rag_document_page',
                'ordering': ['document', 'page_number'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='rag_documen_documen_5b7dfe_idx')],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
