# Generated by Django 4.2.21 on 2025-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membership',
            name='core_member_user_id_5b6d13_idx',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_org',
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='core_member_user_id_3b8c6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_membership'),
        ),
    ]
