# Generated by Django 4.2.26 on 2025-11-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorycleanuppolicy',
            name='agent_session_retention_days',
        ),
        migrations.RemoveField(
            model_name='memorycleanuppolicy',
            name='preserve_agent_reasoning',
        ),
        migrations.RemoveField(
            model_name='memoryusagestats',
            name='agent_entries_count',
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool'), ('function', 'Function')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='source_entity_type',
            field=models.CharField(blank=True, help_text="Source type: 'prompt', 'workflow_step', 'tool_execution', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='contextsession',
            name='entity_type',
            field=models.CharField(db_index=True, help_text="Entity type: 'prompt_session', 'workflow_execution', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='contextsummarycache',
            name='summary_type',
            field=models.CharField(choices=[('conversation', 'Conversation Summary'), ('tool_usage', 'Tool Usage Summary')], default='conversation', max_length=30),
        ),
    ]
