# Generated by Django 4.2.25 on 2025-10-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorycleanuppolicy',
            name='preserve_workflow_state',
        ),
        migrations.RemoveField(
            model_name='memorycleanuppolicy',
            name='workflow_session_retention_days',
        ),
        migrations.RemoveField(
            model_name='memoryusagestats',
            name='workflow_entries_count',
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('agent', 'Agent'), ('tool', 'Tool'), ('function', 'Function')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contextsession',
            name='session_type',
            field=models.CharField(choices=[('chat', 'Chat Session'), ('agent', 'Agent Session'), ('custom', 'Custom Session')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contextsummarycache',
            name='summary_type',
            field=models.CharField(choices=[('conversation', 'Conversation Summary'), ('agent_reasoning', 'Agent Reasoning Summary'), ('tool_usage', 'Tool Usage Summary')], default='conversation', max_length=30),
        ),
        migrations.AlterField(
            model_name='contexttransition',
            name='transition_type',
            field=models.CharField(choices=[('cost_optimization', 'Cost Optimization'), ('quality_upgrade', 'Quality Upgrade'), ('context_window_constraint', 'Context Window Constraint'), ('model_switch', 'Model Switch'), ('user_preference', 'User Preference')], max_length=30),
        ),
    ]
